import { StyleSheet } from "react-native";
import { theme } from "../../util/theme";

export const deleteAccountStyles = StyleSheet.create({
  deleteAccountWrapper: {
    width: "100%",
    height: "100%",
    fontFamily: "Poppins",
    backgroundColor: "pink",
  },
  deleteAccountContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
    height: "100%",
    paddingTop: 50,
  },
  navigationContainer: {
    width: "100%",
    flex: 0.2,
    // paddingTop: 50,
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "flex-start",
  },
  navigationContainerImageTextWrapper: {
    paddingLeft: 20,
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "flex-start",
  },
  navigationImage: {
    width: 30,
    height: 27,
    marginLeft: 10,
    marginRight: 10,
    marginTop: 10,
  },
  navigationText: {
    fontSize: 24,
    fontWeight: "bold",
    color: theme.white,
  },
  contentContainer: {
    width: "100%",
    flex: 0.8,
    backgroundColor: theme.white,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "flex-start",
    paddingLeft: 40,
    paddingRight: 40,
    paddingTop: 20,
    marginTop: 20,
  },
  contentTitle: {
    fontSize: 24,
    fontWeight: "bold",
  },
  contentDescription: {
    fontSize: 14,
    fontWeight: "regular",
  },
  contentScrollView: {
    width: "100%",
    height: "100%",
    marginTop: 20,
  },
  content: {
    fontSize: 14,
    color: theme.black,
  },
  deleteAccountOptions: {
    width: "100%",
    backgroundColor: "white",
    marginTop: 20,
    elevation: 5,
    borderRadius: 20,
    paddingTop: 15,
    paddingBottom: 50,
  },
  deleteAccountOptionsWrapper: {
    backgroundColor: theme.primary,
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "center",
  },
  optionsCard: {
    width: "100%",
    height: 60,
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    paddingLeft: 10,
    borderBottomColor: "#00000030",
  },
  optionsCardSelected: {
    backgroundColor: theme.primary,
  },
  optionsCardUnSelected: {
    backgroundColor: theme.white,
  },
  optionText: {
    fontSize: 16,
  },
  optionsCardOthers: {
    width: "100%",
    height: 90,
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    paddingLeft: 10,
    borderBottomColor: "#00000030",
    paddingTop: 10,
    paddingBottom: 10,
  },
  optionCardExemption: {
    width: "80%",
    display: "flex",
    flexDirection: "column",
    // justifyContent: "flex-start",
  },
  optionTextOther: {
    fontSize: 16,
    marginTop: 5,
    marginBottom: 5,
  },
  otherReasonField: {
    height: 80,
    width: "100%",
    backgroundColor: "white",
    borderWidth: 0.3,
    borderColor: "#00000040",
    borderRadius: 10,
    elevation: 3,
    paddingLeft: 10,
  },
  footerContainer: {
    width: "100%",
    backgroundColor: "white",
    paddingLeft: 40,
    paddingRight: 40,
  },
});
