import { StyleSheet } from "react-native";
import { theme } from "../util/theme";

export const offerWallStyles = StyleSheet.create({
  offerWallWrapper: {
    width: "100%",
    height: "100%",
    backgroundColor: "pink",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "column",
  },
  navigationSection: {
    flex: 0.2,
    width: "100%",
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "center",
    paddingHorizontal: 30,
    paddingVertical: 10,
  },
  navigationSectionText: {
    fontSize: 30,
    fontWeight: "bold",
    color: "white",
    marginTop: 10,
  },
  bodySection: {
    flex: 0.5,
    width: "100%",
    height: "100%",
  },
  offersContainerWrapper: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-start",
  },
  offersContainer: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-start",
  },
  offer: {
    marginHorizontal: 30,
    height: 160,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    borderRadius: 20,
    marginVertical: 5,
    overflow: "hidden",
  },
  offerUnSelected: {
    marginHorizontal: 30,
    height: 160,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    borderRadius: 20,
    marginVertical: 5,
    borderColor: theme.tertirary,
    borderWidth: 1,
    overflow: "hidden",
  },
  leftSection: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
  },
  titleSectionWrapper: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContentc: "center",
    flex: 1,
  },
  titleSection: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
    paddingHorizontal: 10,
  },
  title: {
    fontSize: 25,
    color: "white",
    fontWeight: "bold",
    marginLeft: 10,
  },
  statusContainer: {
    backgroundColor: theme.offerStatus,
    padding: 10,
    borderRadius: 5,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  status: {
    color: "white",
    fontSize: 10,
    fontWeight: "bold",
  },
  contentSection: {
    width: "100%",
    flex: 1,
    display: "flex",
    alignItems: "flex-start",
    paddingHorizontal: 15,
    justifyContent: "flex-start",
  },
  contentItem: {
    color: "white",
    fontSize: 18,
    fontWeight: "regular",
  },
  rightSection: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
  },
  priceTag: {
    fontSize: 55,
    fontWeight: "bold",
    color: "white",
  },
  footerSection: {
    width: "100%",
    flex: 0.3,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 30,
  },
  terms: {
    fontSize: 9,
    fontWeight: "regular",
    color: "white",
    marginBottom: 20,
  },
  purchaseButton: {
    marginTop: 50,
  },
});
