import { StyleSheet } from "react-native";
import { Colors } from "../../../constants/Colors";

const styles = StyleSheet.create({
  toDoContainer: {
    width: "100%",
    height: "100%",
    marginTop: 30,
    display: "flex",
    backgroundColor: "#F5F5F5",
  },
  header: {
    flex: 0.05,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 5,
  },
  navSection: {
    flex: 1,
  },
  title: {
    color: "black",
    fontWeight: "600",
    fontSize: 18,
    textAlign: "center",
  },
  headerSection: {
    flex: 1,
  },
  optionsSection: {
    flex: 1,
    marginRight: 10,
    color: "black",
    opacity: 0,
  },
  optionsText: {
    textAlign: "right",
  },
  backButtonText: {
    fontSize: 16,
    color: "#007BFF",
    fontWeight: "500",
    marginLeft: 20,
    marginTop: 3,
  },
  body: {
    flex: 0.8,
  },
  bodyTitleSection: {
    width: "100%",
    height: 50,
    marginBottom: 10,
    paddingRight: 20,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  bodyTitleSectionLeftSection: {
    width: "100%",
    display: "flex",
    flex: 0.9,
  },
  bodyTitleSectionRightSection: {
    width: "100%",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    flex: 0.1,
  },
  searchButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    marginTop: 5,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  searchIcon: {
    width: 25,
    height: 25,
    marginTop: 5,
    marginBottom: 15,
  },
  searchBar: {
    width: "100%",
    height: 50,
    marginTop: -10,
    padding: 10,
    marginBottom: 5,
  },
  serchField: {
    width: "100%",
    height: 35,
    backgroundColor: "#333333",
    paddingLeft: 10,
    borderRadius: 10,
    color: "white",
  },
  bodyTitle: {
    fontSize: 35,
    marginLeft: 20,
    fontWeight: 700,
    marginTop: 15,
    height: 50,
    paddingTop: 5,
    color: "black",
  },
  listItemEditable: {
    width: "93%",
  },
  listItemUnEditable: {
    width: "93%",
  },
  authorTitle: {
    fontSize: 10,
    marginBottom: 5,
  },
  listItemWrapper: {
    display: "flex",
    flexDirection: "row",
    alignItems: "start",
    justifyContent: "space-between",
    marginLeft: 15,
    backgroundColor: "white",
    borderRadius: 10,
    margin: 2,
    paddingLeft: 15,
  },
  onEditlistItem: {
    borderWidth: 1,
    borderStyle: "dashed",
  },
  editIcon: {
    width: 25,
    height: 25,
  },
  unFilledStar: {
    opacity: 0.3,
  },
  selectionSection: {
    flex: 0.1,
    height: "100%",
    display: "flex",
    alignItems: "center",
  },
  textSection: {
    flex: 0.6,
    height: "100%",
  },
  actionsSection: {
    flex: 0.4,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    marginRight: 10,
  },
  nonSelectable: {
    userSelect: "none",
    opacity: 0,
  },
  editIconWrapper: {
    width: 35,
    height: 35,
    marginLeft: 2,
    marginRight: 2,
    borderRadius: 50,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  editDeleteActionContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
  },
  listItemTitle: {
    color: "black",
    fontWeight: "700",
    fontSize: 18,
    height: 30,
  },
  listItemDescription: {
    color: "grey",
    fontSize: 14,
    marginTop: -5,
  },
  listCategoryTitle: {
    color: "grey",
    fontSize: 14,
    marginTop: -3,
    marginLeft: 10,
  },
  categoryContainer: {
    width: "100%",
    display: "flex",
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "flex-start",
  },
  labelIcon: {
    width: 25,
    height: 25,
  },
  shareContainer: {
    width: "100%",
    height: 40,
    backgroundColor: "#80808030",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 20,
  },
  shareContainerImage: {
    width: 20,
    height: 20,
  },
  shareContainerText: {
    fontSize: 16,
    color: "#007BFF",
    marginLeft: 10,
  },
  footer: {
    flex: 0.05,
  },
  addItemButton: {
    width: 60,
    height: 60,
    backgroundColor: "white",
    elevation: 2,
    borderRadius: 100,
    position: "absolute",
    bottom: 70,
    right: 30,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  addItemIcon: {
    fontSize: 35,
    fontWeight: "400",
    marginBottom: 4,
    color: "#007BFF",
  },
  listModalWrapper: {
    width: "100%",
    height: "100%",
    backgroundColor: "#00000030",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  listModalContainer: {
    width: "90%",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#D3D3D360",
    marginLeft: 20,
    marginTop: 15,
    paddingBottom: 5,
    paddingTop: 10,
    borderRadius: 10,
  },
  fieldsSection: {
    flex: 0.9,
    marginLeft: 20,
  },
  validateSection: {
    flex: 0.1,
    marginRight: 10,
  },
  emptyListText: {
    textAlign: "center",
  },
  categoryTitle: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-start",
    flexDirection: "row",
    textAlign: "left",
    marginLeft: 20,
    marginBottom: 2,
    marginTop: 5,
    fontSize: 16,
    fontWeight: "bold",
  },
  submitIcon: {
    width: 25,
    height: 25,
    marginTop: 5,
  },
  discardIcon: {
    height: 25,
    width: 25,
  },
  modalSubmitButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    marginTop: 5,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  modalSubmiteButtonDisabled: {
    width: 90,
    height: 30,
    borderRadius: 15,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "grey",
  },
  listModalTitle: {
    fontSize: 25,
    marginBottom: 10,
    fontWeight: "500",
    color: "black",
  },
  modalInputField: {
    width: "80%",
    marginBottom: -5,
  },
  modalInputFieldTitle: {
    fontWeight: "500",
  },
  modalSubmitButtonText: {
    color: "white",
    fontWeight: "600",
    elevation: 2,
  },
  options: {
    backgroundColor: "white",
    borderRadius: 10,
    margin: 5,
  },
  flatListStyles: {
    overflow: "hidden",
    alignItems: "center",
  },
  bodyList: {
    flex: 1,
  },
  bodyScrollViewStyles: {
    flex: 1,
  },
  tapToAddWrapper: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
    marginBottom: 10,
  },
  tapToAddContainer: {
    width: "90%",
    backgroundColor: Colors.light.buttonBackground,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 10,
    borderRadius: 10,
  },
  tapToAddText: { color: "white", fontSize: 16 },
  tapToAddHighlight: {
    color: "white",
    fontWeight: "bold",
  },
});

export default styles;
